### ISSUE TITLE
Logger doesn't write to DB when deployed to server

### ISSUE THREAD

**Issue by davedodea** [randysimpson/express-log-psql#1]
Firstly, many thanks for this very useful package 👏 

- I have a strange issue whereby the logger writes to a remote DB just fine when running locally on my express app.
- Up until recently it also used to write to the DB fine when the app was deployed on a server. However, for some reason lately, it has stopped writing to the DB. 
- The below code sample from my express app is identical on both local and deployed server but only the local server is writing. Note, the logger does not throw any errors etc when it fails to write.

```js
try {
  /* Custom logging tokens */

  // Capture user email
  logger.token('created_by', (req) => {
    // If user is not yet logged in, mark as anonymous
    if (!req.user) {
      return 'ANONYMOUS';
    }
    return req.user.email;
  });

  // Capture user's account_id
  logger.token('account_id', (req) => {
    // If user is not yet logged in, mark as anonymous
    if (!req.user) {
      return 'ANONYMOUS';
    }
    return req.user.accountId;
  });

  // If user is logging in, redact PW from logs
  logger.token('req_body', (req) => {
    // Redact password when accessing the auth route
    if (req.originalUrl === '/authenticate') {
      req.body.password = 'REDACTED';
      return req.body;
    }
    return req.body;
  });

  // Log on all app routes
  app.use(
    logger(
      ':created_by :account_id :req_body :method :url :status :remote-addr :response-time :http-version :remote-user :res[content-length] :referrer :user-agent ',
      {
        url: `postgresql://${process.env.DB_USER}:${process.env.DB_PASSWORD}@${process.env.DB_HOST}:${process.env.DB_PORT}/${process.env.DB_NAME}`,
        table: 'api_log',
      }
    )
  );
} catch (error) {
  console.log('ERROR: ', error);
}
```

Have you seen anything like this behaviour previously? It's strange as nothing is different between my local and server implementation.

**Comment by rsimpson-cb** [comment]
I agree that it's strange to be different from the local and the server implementation.  Seems like the server is having a timeout when reaching out to the DB.  A few places to check:
* Verify that the server implementation environment variables are correct. `DB_USER`, `DB_PASSWORD`, `DB_HOST`, and `DB_PORT`
* Check the DNS on the server to be sure it can perform a successful lookup on the `DB_HOST`
* Check that the server implementation can access the DB and it can connect successfully using the connection string.  For this you could create an app that uses the connection string to query the api_log table or something just for a test.

**Comment by davedodea** [comment]
Closing as it doesn't look like an issue with this package, but rather our server setup. Thanks, @rsimpson-cb
